### ISSUE TITLE
Make extension (or maybe all) pages inspectable via ADB

### ISSUE THREAD

**Issue by derjanb** [yandex/browser-extensions#3]
It would be nice if one could debug the extension pages via ADB and "chrome://inspect" at a desktop browser. Maybe this should also be configurable.

I'm sorry that I can not report more severe issues, but the browser is working quite good here. Even the Tampermonkey test suite runs without major issues.

**Comment by pavor84** [comment]
Could you, please, download the latest Yandex.Browser Alpha version from Google Play
https://play.google.com/store/apps/details?id=com.yandex.browser.alpha
Extensions should be enabled there (you need to connect to internet, quit and restart it to make them switch on). There should also be Debugging over USB option in settings as I described before.

**Comment by derjanb** [comment]
This is working great now. Thanks!
