### ISSUE TITLE
chrome.tabs.getSelected doesn't work for tabs opened from anchors with target="_blank"

### ISSUE THREAD

**Issue by derjanb** [yandex/browser-extensions#4]
Steps to reproduce:

* Install TM
* Install https://greasyfork.org/de/scripts/735-anti-adblock-killer-reek -> it runs at every page, therefor the action menu badge should always show 1 or higher
* Open http://tampermonkey.net/changelog.php and open the action menu and veryify that the script is running
* Now click at a yellow link at the changelog page (i.e. "not completely working")
* A new tabs opens that shows no TM script running

adb logcat shows:

    [INFO:CONSOLE(0)] "Unchecked runtime.lastError while running tabs.getSelected: No selected tab

**Comment by pavor84** [comment]
Hi, derjanb

This bug should not appear in the latest alpha version of Yandex.Browser. Could you, please, check it?

**Comment by derjanb** [comment]
@pavor84 Sorry for the delay. Yes, it's working fine now. Thanks.
