### ISSUE TITLE
chrome.downloads.download API

### ISSUE THREAD

**Issue by Feverqwe** [yandex/browser-extensions#5]
Downloads API не работает? При попытке использовать, в консоль выводит:

Unchecked runtime.lastError while running downloads.download: USER_CANCELED

**Comment by notWhaleB** [comment]
Hi,

Downloads API isn't fully working at this moment, according to the results of the test https://yandex.github.io/browser-extensions/. `[Download-Pause-Resume]` test which is failed now, requires three methods: `download()`, `pause()` and `resume()`, and there is an issue with pausing a download, but just `download()` method should work correctly, you can start a download from browser API but can't pause and hence resume it.

Could you please run `Browser API Test` extension from repo, in directory `api-test-extension/` and attach HTML report (generated by Save Report button) and console output after complete testing, also model of your device will be very helpful. In case of correctly working `download()` method, it is assumed that you will have `logo.svg` file in your downloads folder after all the tests are done.

**Comment by Feverqwe** [comment]
Yes test write that download work.. logo.svg downloaded. 
I am trying to understand what is wrong with my code.

Report and console log:
[report_console.zip](https://github.com/yandex/browser-extensions/files/452139/report_console.zip)

**Comment by Feverqwe** [comment]
I create simple extension for test.
Install extension, open ya.ru and click link "Download logo.svg"

[testDownload.zip](https://github.com/yandex/browser-extensions/files/452272/testDownload.zip)

**Comment by notWhaleB** [comment]
Test `[Method Call] download` just calling the method and checking exception. File `logo.svg` downloads in `[Download-Pause-Resume]` test. 

I've found what is wrong. In spite of the fact that download has been started, `chrome.downloads.download()` in callback returns `undefined` and raise the error USER_CANCELED.

**Comment by Feverqwe** [comment]
Do you try use test extension? It don't only error in console. File don't start download.

**Comment by notWhaleB** [comment]
Your case even causes crash of the browser. Thank you for this example! We'll investigate this issue.

**Comment by pavor84** [comment]
Hi, Feverqwe

This bug should be fixed in latest alpha version of Yandex.Browser 16.9.1.1498.
Please, check if it works now in your case.

**Comment by Feverqwe** [comment]
Hi! I tested a few days ago. Yes, it work, thx!
