### ISSUE TITLE
Keyboard in extension popup

### ISSUE THREAD

**Issue by Feverqwe** [yandex/browser-extensions#6]
When I try enter text in input in popup, keyboard is not show.

I use this extension for test 
https://chrome.google.com/webstore/detail/mapmknaogodpakjopdhmdcilahbfbjpc

**Comment by Bryunyon** [comment]
Hi,
I have installed the Extensions Switcher from your link but have not found any inputs in popup.
Could you please attach a screenshot of popup with the input field?

**Comment by Feverqwe** [comment]
Screenshot:
![screenshot_20160908-114014](https://cloud.githubusercontent.com/assets/891534/18339486/31b65e66-75b9-11e6-9518-2ddc1b91e71b.png)

**Comment by Bryunyon** [comment]
How do you make editable groups? I have not been able to get it neither on mobile nor on desktop.

**Comment by Feverqwe** [comment]
I move extension icon to top of the list (out of "Extension" group). And was created new group.

**Comment by Bryunyon** [comment]
Thanks! Got it and confirm the bug

**Comment by notWhaleB** [comment]
Hi,

There is script which included in extension, named `popup.js`, it replacing default listener for `click` event and stopping further propagation using [Event.stopPropagation()](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation). So event can't be handled as expected by default. 

Nonappearance of the virtual keyboard is normal behaviour from the browser side in case of stopping event propagation by developer.

```javascript
b = mono.create("input", {
                    checked: a.enabled,
                    disabled: !a.mayDisable,
                    type: "checkbox",
                    on: [["change", function(c) {
                        var b = this;
                        if (b.disabled)
                            this.checked = 
                            a.enabled;
                        else
                            return b.disabled = !0,
                            chrome.management.setEnabled(a.id, this.checked, function() {
                                b.disabled = !1;
                                a.enabled = b.checked;
                                e();
                                "byGroup" !== c.detail && d.getGroup(f).dispatchEvent(new CustomEvent("updateState"))
                            })
                    }
                    ], ["click", function(a) {
/* Here --> */          a.stopPropagation()
                    }
                    ]]
```

**Comment by Feverqwe** [comment]
I write simple test extension https://yadi.sk/d/m6tbSPiMuuAd5
It just input in html page. And keyboard don't show.

**Comment by notWhaleB** [comment]
Oh, Indeed. It seems that issue more complex then. For example, LastPass extension opening popup too but keyboard appearing for input elements.

**Comment by Bryunyon** [comment]
Hi,

We have published Yandex Browser Beta with the fix for virtual keyboard in extension popup.
https://play.google.com/store/apps/details?id=com.yandex.browser.beta

Could you please check?

**Comment by Feverqwe** [comment]
Install build 1.1156 bug is not fixed.

**Comment by Bryunyon** [comment]
It seems that Google Play is not fully update the version.
The version with fix should be 16.9.0.1247 from September, 13th

**Comment by Feverqwe** [comment]
Install build 1.290б the problem is solved. Thx!

**Comment by Bryunyon** [comment]
Thanks for the quick checking!
I have create separate issue for uninstall dialog
https://github.com/yandex/browser-extensions/issues/7
